name: dartevel_framework
version: 0.0.0
description: >-
  a fullstack web framework like laravel for dart language

repository: https://github.com/dartevel/framework
authors:
  - Miladimos <miladimos@outlook.com>
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  http: ^0.13.3
  crypto: ^3.0.1
  args: ^2.2.0
  os_detect: ^2.0.0

dev_dependencies:
  test: ^1.17.11
  